version: "3.8"

services:
 mysqldb:
   container_name: mysqldb
   image: mysql
   ports:
     - "3306"
 environment:
    - MYSQL_DATABASE: mysqldb
    - MYSQL_ROOT_PASSWORD: root
 

 webapp:
  container_name: springboot
  build:
   container: ./
   dockerfile: dockerfile
   ports:
    - 8080:8080
   depends_on:
     -mysql_db

